version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: '@Vtr7122349'
    expose:
      - "1433"
    ports:
      - "192.168.0.104:1433:1433"
    restart: always
  server:
    build: .
    command: npm start
    expose:
      - "3333"
    ports:
      - "192.168.0.104:3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db
